import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Pages/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Landing Page",
  description: "Generated by Siddarth 9310674707",
  icons: {
    icon: ["/Screenshot 2024-05-26 141259.png"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
